# Dependencies
# markdown:         redcarpet
markdown: kramdown
# highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title: Cryptomeria
email: Sohkawara@mail.greenriver.edu
tagline: 'A Jekyll theme'
description: >-
  soarcreator.github.io
url: /
baseurl: /

author:
  name: 'soarcreator'
  github: https://github.com/soarcreator
  twitter: https://twitter.com/soarcreator


paginate:         5

# Custom vars
version:          0.0.1